Repository fjprog101/AT15, pull requests merged in 2022-03, with the labels that each got.

#38 Saul/class item
  src/main/java/org/fundacionjala/at15/pokemon/Item.java
Labels: first classes

#50 Completed the function of restoring the health of a pokemon and added…
  src/main/java/org/fundacionjala/at15/pokemon/HealingPotion.java
  src/test/java/org/fundacionjala/at15/pokemon/HealingPotionTest.java
Labels: first classes

#99 Added ID to pokemon command creation
  src/main/java/org/fundacionjala/at15/pokemon/ID/Identifier.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/PokemonCli.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/PokemonCommands.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/SubCommandsCreate.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/TrainerCommands.java
Labels: enhancement

#108 Saul/town refactor
  src/main/java/org/fundacionjala/at15/pokemon/Town.java
  src/test/java/org/fundacionjala/at15/pokemon/TownTest.java
Labels: enhancement

#111 fixed PokemonCommands & TrainerCommands problems
  src/main/java/org/fundacionjala/at15/pokemon/commands/PokemonCommands.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/TrainerCommands.java
Labels: bug

#155 Agustin/REFACTOR
  META-INF/MANIFEST.MF
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/org/fundacionjala/at15/pokemon/Battle.java
  src/main/java/org/fundacionjala/at15/pokemon/TrainerBattle.java
  src/main/java/org/fundacionjala/at15/pokemon/WildPokemonBattle.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/CreateCLI.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/PokemonCLI.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/PokemonCli.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/SubCommandCatch.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/behavior/Catch.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/behavior/Fight.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/behavior/Learn.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/behavior/PokemonBehavior.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/behavior/Select.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/behavior/TrainerBehavior.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/behavior/Use.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/create/CreateCLI.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/create/CreatePokemon.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/create/CreateTown.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/create/CreateTrainer.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/create/CreateTrainerBattle.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/create/CreateWildPokemonBattle.java
  src/main/java/org/fundacionjala/at15/pokemon/commands/query/QueryCLI.java
  src/test/java/org/fundacionjala/at15/pokemon/WildPokemonBattleTest.java
  src/test/java/org/fundacionjala/at15/pokemon/commands/CreatePokemonTest.java
  src/test/java/org/fundacionjala/at15/pokemon/commands/CreateTownTest.java
  src/test/java/org/fundacionjala/at15/pokemon/commands/CreateTrainerBattleTest.java
  src/test/java/org/fundacionjala/at15/pokemon/commands/CreateTrainerTest.java
  src/test/java/org/fundacionjala/at15/pokemon/commands/CreateWildPokemonBattleTest.java
  src/test/java/org/fundacionjala/at15/pokemon/commands/SubCommandLearnTest.java
Labels: documentation, enhancement
